apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::801042636421:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HAVKAGPXXZOM
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::801042636421:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T07:54:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3572"
  uid: 6b64ffcb-a5c2-4a4c-9faa-757dd408afe4
